### ISSUE TITLE
CONNECTION FAILED, YOU ARE BANNED

### ISSUE THREAD

**Issue by kakashikuna** [dwwe2017/teamspeak-interface#4]
Hallo, 

der TeamSpeak Server bannt regelmäßig das TSI.
Das Problem betrifft nur das TSI.
Die IP ist in der White List sowie B_CLIENT_IGNORE_ANTIFLOOD ist gesetzt.

Grüße

**Comment by dwwe2017** [comment]
Grüße, welche IP ist denn in der Whitelist eingetragen? Die auf der das TSI läuft oder die des TS Servers? Ich frag nur zur Sicherheit. Es liegt aber zu 100% an der Konfiguration, hier gibt es in der Regel keine Probleme.

**Comment by kakashikuna** [comment]
Habe die IP des Servers eingetragen wo das TSI drauf läuft in die Whitelist des TS Servers.
Es funktioniert und dann geht es wieder nicht und dann geht es irgendwann wider.

2023-01-21 17:10:01.346521|INFO    |Query         |   |query from xxxxx xxx.xxx.xxx.xxx:xxxxx attempted to login with account "xx" and failed!

**Comment by dwwe2017** [comment]
Gibt es evtl. sonst noch irgendeine Art Firewall auf dem Server wo der TS läuft? Was steht im Log des TS Servers dazu? Nutzt du den serveradmin als root oder einen anderen Query Client um dich mit dem TS Server zu verbinden?

**Comment by dwwe2017** [comment]
Wie sieht es aus? Problem behoben? Wenn ja, woran lag es?
